"""Changed database to mysql

Revision ID: 234a08bee9b9
Revises: 
Create Date: 2018-12-27 20:15:54.962194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234a08bee9b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=20), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('make', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_tag'), 'vehicle', ['tag'], unique=True)
    op.create_index(op.f('ix_vehicle_vin'), 'vehicle', ['vin'], unique=True)
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=128), nullable=False),
    sa.Column('origpath', sa.String(length=128), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    op.drop_index(op.f('ix_vehicle_vin'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_tag'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('equipment')
    # ### end Alembic commands ###
