"""Changed User.image_file string lingth

Revision ID: c507469f2e04
Revises: 234a08bee9b9
Create Date: 2018-12-27 20:27:03.493645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c507469f2e04'
down_revision = '234a08bee9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'picture', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(None, 'picture', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.drop_constraint(None, 'picture', type_='foreignkey')
    # ### end Alembic commands ###
